---
# tasks file for engonzal.proxmox
- include_tasks: inventory.yml

- name: Get existing container facts
  include_tasks: inventory_exists.yml
  when: pve_container_exists

- name: Provision Container
  include_tasks: provision.yml
  when: pve_container_exists | bool == False

- name: Configure mounts
  include_tasks: mounts.yml
  when:
    - pve_container_exists | bool == False 
    - pve_custom_mounts is defined

- name: Start Container if it was just created
  proxmox:
    vmid: "{{ pve_vmid | default(pve_new_vmid) | int }}"
    api_user: "{{ pve_apiuser }}"
    api_password: "{{ pve_apipass}}"
    api_host: "{{ pve_api_host }}"
    state: started
  delegate_to: localhost
  register: pve_info_state
  when: 
    - pve_container_exists | bool == False
    - pve_info.changed 
    - pve_ct_state == "started"

