---
- name: Set vmid var (existing)
  set_fact:
    pve_new_vmid: "{{ pve_info.msg.split('exists and has ID number ')[1] }}"
  when:
    - not pve_info.failed
    - not pve_info.changed

- name: Get container config
  command: pct config {{ pve_vmid | default (pve_new_vmid) }}
  register: pve_info_mounts
  delegate_to: "{{ pve_node }}"
  changed_when: false

- name: Manually add bind mounts to container
  command: "pct set {{ pve_vmid | default(pve_new_vmid) }} -{{ item.key }} {{ item.value }}"
  loop: "{{ pve_custom_mounts | default({ })|dict2items }}"
  when:
    - pve_custom_mounts is defined
    - not pve_info.failed
    - item.key not in pve_info_mounts.stdout
  delegate_to: "{{ pve_node }}"
  notify: Start container
