- name: Set vmid var (existing)
  set_fact:
    pve_new_vmid:  "{{ pve_info.msg.split('exists and has ID number ')[1] }}"
  when: 
    - pve_info.failed | bool == false
    - pve_info.changed | bool == false

- name: Get container config
  command: pct config {{ pve_vmid | default (pve_new_vmid)}}
  register: pve_info_mounts
  delegate_to: "{{ pve_node }}"
  changed_when: false

- name: Manually add bind mounts to container
  command: "pct set {{ pve_vmid | default(pve_new_vmid) }} -{{ item.key }} {{ item.value }}"
  loop: "{{ pve_custom_mounts | default({})|dict2items }}"
  when:
    - pve_custom_mounts is defined
    - pve_info.failed | bool == false
    - item.key not in pve_info_mounts.stdout
  delegate_to: "{{ pve_node }}"
